import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// sortOrder: 1〜20 = 日本で外国人雇用が多い国・主要国を優先表示
// 100 = その他（五十音順で表示）
const countries = [
  // ===== 優先表示（日本での就労者が多い順） =====
  { code: 'JP', name: '日本',                     nameEn: 'Japan',                        sortOrder: 1  },
  { code: 'CN', name: '中国',                     nameEn: 'China',                        sortOrder: 2  },
  { code: 'VN', name: 'ベトナム',                 nameEn: 'Vietnam',                      sortOrder: 3  },
  { code: 'PH', name: 'フィリピン',               nameEn: 'Philippines',                  sortOrder: 4  },
  { code: 'BR', name: 'ブラジル',                 nameEn: 'Brazil',                       sortOrder: 5  },
  { code: 'NP', name: 'ネパール',                 nameEn: 'Nepal',                        sortOrder: 6  },
  { code: 'KR', name: '韓国',                     nameEn: 'South Korea',                  sortOrder: 7  },
  { code: 'ID', name: 'インドネシア',             nameEn: 'Indonesia',                    sortOrder: 8  },
  { code: 'MM', name: 'ミャンマー',               nameEn: 'Myanmar',                      sortOrder: 9  },
  { code: 'TH', name: 'タイ',                     nameEn: 'Thailand',                     sortOrder: 10 },
  { code: 'BD', name: 'バングラデシュ',           nameEn: 'Bangladesh',                   sortOrder: 11 },
  { code: 'IN', name: 'インド',                   nameEn: 'India',                        sortOrder: 12 },
  { code: 'TW', name: '台湾',                     nameEn: 'Taiwan',                       sortOrder: 13 },
  { code: 'US', name: 'アメリカ合衆国',           nameEn: 'United States',                sortOrder: 14 },
  { code: 'GB', name: 'イギリス',                 nameEn: 'United Kingdom',               sortOrder: 15 },
  { code: 'CA', name: 'カナダ',                   nameEn: 'Canada',                       sortOrder: 16 },
  { code: 'AU', name: 'オーストラリア',           nameEn: 'Australia',                    sortOrder: 17 },
  { code: 'FR', name: 'フランス',                 nameEn: 'France',                       sortOrder: 18 },
  { code: 'DE', name: 'ドイツ',                   nameEn: 'Germany',                      sortOrder: 19 },
  { code: 'LK', name: 'スリランカ',               nameEn: 'Sri Lanka',                    sortOrder: 20 },

  // ===== その他（sortOrder: 100、五十音順） =====
  { code: 'AF', name: 'アフガニスタン',           nameEn: 'Afghanistan',                  sortOrder: 100 },
  { code: 'ZA', name: '南アフリカ',               nameEn: 'South Africa',                 sortOrder: 100 },
  { code: 'SS', name: '南スーダン',               nameEn: 'South Sudan',                  sortOrder: 100 },
  { code: 'AL', name: 'アルバニア',               nameEn: 'Albania',                      sortOrder: 100 },
  { code: 'DZ', name: 'アルジェリア',             nameEn: 'Algeria',                      sortOrder: 100 },
  { code: 'AR', name: 'アルゼンチン',             nameEn: 'Argentina',                    sortOrder: 100 },
  { code: 'AM', name: 'アルメニア',               nameEn: 'Armenia',                      sortOrder: 100 },
  { code: 'AZ', name: 'アゼルバイジャン',         nameEn: 'Azerbaijan',                   sortOrder: 100 },
  { code: 'IE', name: 'アイルランド',             nameEn: 'Ireland',                      sortOrder: 100 },
  { code: 'IS', name: 'アイスランド',             nameEn: 'Iceland',                      sortOrder: 100 },
  { code: 'AO', name: 'アンゴラ',                 nameEn: 'Angola',                       sortOrder: 100 },
  { code: 'AG', name: 'アンティグア・バーブーダ', nameEn: 'Antigua and Barbuda',           sortOrder: 100 },
  { code: 'AD', name: 'アンドラ',                 nameEn: 'Andorra',                      sortOrder: 100 },
  { code: 'YE', name: 'イエメン',                 nameEn: 'Yemen',                        sortOrder: 100 },
  { code: 'IL', name: 'イスラエル',               nameEn: 'Israel',                       sortOrder: 100 },
  { code: 'IT', name: 'イタリア',                 nameEn: 'Italy',                        sortOrder: 100 },
  { code: 'IQ', name: 'イラク',                   nameEn: 'Iraq',                         sortOrder: 100 },
  { code: 'IR', name: 'イラン',                   nameEn: 'Iran',                         sortOrder: 100 },
  { code: 'UG', name: 'ウガンダ',                 nameEn: 'Uganda',                       sortOrder: 100 },
  { code: 'UA', name: 'ウクライナ',               nameEn: 'Ukraine',                      sortOrder: 100 },
  { code: 'UZ', name: 'ウズベキスタン',           nameEn: 'Uzbekistan',                   sortOrder: 100 },
  { code: 'UY', name: 'ウルグアイ',               nameEn: 'Uruguay',                      sortOrder: 100 },
  { code: 'AE', name: 'アラブ首長国連邦',         nameEn: 'United Arab Emirates',         sortOrder: 100 },
  { code: 'EC', name: 'エクアドル',               nameEn: 'Ecuador',                      sortOrder: 100 },
  { code: 'EG', name: 'エジプト',                 nameEn: 'Egypt',                        sortOrder: 100 },
  { code: 'EE', name: 'エストニア',               nameEn: 'Estonia',                      sortOrder: 100 },
  { code: 'SZ', name: 'エスワティニ',             nameEn: 'Eswatini',                     sortOrder: 100 },
  { code: 'ER', name: 'エリトリア',               nameEn: 'Eritrea',                      sortOrder: 100 },
  { code: 'SV', name: 'エルサルバドル',           nameEn: 'El Salvador',                  sortOrder: 100 },
  { code: 'ET', name: 'エチオピア',               nameEn: 'Ethiopia',                     sortOrder: 100 },
  { code: 'AT', name: 'オーストリア',             nameEn: 'Austria',                      sortOrder: 100 },
  { code: 'NL', name: 'オランダ',                 nameEn: 'Netherlands',                  sortOrder: 100 },
  { code: 'OM', name: 'オマーン',                 nameEn: 'Oman',                         sortOrder: 100 },
  { code: 'GH', name: 'ガーナ',                   nameEn: 'Ghana',                        sortOrder: 100 },
  { code: 'CV', name: 'カーボベルデ',             nameEn: 'Cabo Verde',                   sortOrder: 100 },
  { code: 'GY', name: 'ガイアナ',                 nameEn: 'Guyana',                       sortOrder: 100 },
  { code: 'KZ', name: 'カザフスタン',             nameEn: 'Kazakhstan',                   sortOrder: 100 },
  { code: 'QA', name: 'カタール',                 nameEn: 'Qatar',                        sortOrder: 100 },
  { code: 'CM', name: 'カメルーン',               nameEn: 'Cameroon',                     sortOrder: 100 },
  { code: 'KH', name: 'カンボジア',               nameEn: 'Cambodia',                     sortOrder: 100 },
  { code: 'GA', name: 'ガボン',                   nameEn: 'Gabon',                        sortOrder: 100 },
  { code: 'GM', name: 'ガンビア',                 nameEn: 'Gambia',                       sortOrder: 100 },
  { code: 'GN', name: 'ギニア',                   nameEn: 'Guinea',                       sortOrder: 100 },
  { code: 'GW', name: 'ギニアビサウ',             nameEn: 'Guinea-Bissau',                sortOrder: 100 },
  { code: 'CY', name: 'キプロス',                 nameEn: 'Cyprus',                       sortOrder: 100 },
  { code: 'KI', name: 'キリバス',                 nameEn: 'Kiribati',                     sortOrder: 100 },
  { code: 'KG', name: 'キルギス',                 nameEn: 'Kyrgyzstan',                   sortOrder: 100 },
  { code: 'CU', name: 'キューバ',                 nameEn: 'Cuba',                         sortOrder: 100 },
  { code: 'GR', name: 'ギリシャ',                 nameEn: 'Greece',                       sortOrder: 100 },
  { code: 'GT', name: 'グアテマラ',               nameEn: 'Guatemala',                    sortOrder: 100 },
  { code: 'KW', name: 'クウェート',               nameEn: 'Kuwait',                       sortOrder: 100 },
  { code: 'CK', name: 'クック諸島',               nameEn: 'Cook Islands',                 sortOrder: 100 },
  { code: 'HR', name: 'クロアチア',               nameEn: 'Croatia',                      sortOrder: 100 },
  { code: 'GD', name: 'グレナダ',                 nameEn: 'Grenada',                      sortOrder: 100 },
  { code: 'KE', name: 'ケニア',                   nameEn: 'Kenya',                        sortOrder: 100 },
  { code: 'CI', name: 'コートジボワール',         nameEn: "Côte d'Ivoire",                sortOrder: 100 },
  { code: 'CR', name: 'コスタリカ',               nameEn: 'Costa Rica',                   sortOrder: 100 },
  { code: 'KM', name: 'コモロ',                   nameEn: 'Comoros',                      sortOrder: 100 },
  { code: 'CO', name: 'コロンビア',               nameEn: 'Colombia',                     sortOrder: 100 },
  { code: 'CG', name: 'コンゴ共和国',             nameEn: 'Republic of the Congo',        sortOrder: 100 },
  { code: 'CD', name: 'コンゴ民主共和国',         nameEn: 'DR Congo',                     sortOrder: 100 },
  { code: 'SA', name: 'サウジアラビア',           nameEn: 'Saudi Arabia',                 sortOrder: 100 },
  { code: 'WS', name: 'サモア',                   nameEn: 'Samoa',                        sortOrder: 100 },
  { code: 'ST', name: 'サントメ・プリンシペ',     nameEn: 'São Tomé and Príncipe',        sortOrder: 100 },
  { code: 'SM', name: 'サンマリノ',               nameEn: 'San Marino',                   sortOrder: 100 },
  { code: 'ZM', name: 'ザンビア',                 nameEn: 'Zambia',                       sortOrder: 100 },
  { code: 'SL', name: 'シエラレオネ',             nameEn: 'Sierra Leone',                 sortOrder: 100 },
  { code: 'DJ', name: 'ジブチ',                   nameEn: 'Djibouti',                     sortOrder: 100 },
  { code: 'JM', name: 'ジャマイカ',               nameEn: 'Jamaica',                      sortOrder: 100 },
  { code: 'GE', name: 'ジョージア',               nameEn: 'Georgia',                      sortOrder: 100 },
  { code: 'SY', name: 'シリア',                   nameEn: 'Syria',                        sortOrder: 100 },
  { code: 'SG', name: 'シンガポール',             nameEn: 'Singapore',                    sortOrder: 100 },
  { code: 'ZW', name: 'ジンバブエ',               nameEn: 'Zimbabwe',                     sortOrder: 100 },
  { code: 'CH', name: 'スイス',                   nameEn: 'Switzerland',                  sortOrder: 100 },
  { code: 'SE', name: 'スウェーデン',             nameEn: 'Sweden',                       sortOrder: 100 },
  { code: 'SD', name: 'スーダン',                 nameEn: 'Sudan',                        sortOrder: 100 },
  { code: 'ES', name: 'スペイン',                 nameEn: 'Spain',                        sortOrder: 100 },
  { code: 'SR', name: 'スリナム',                 nameEn: 'Suriname',                     sortOrder: 100 },
  { code: 'SK', name: 'スロバキア',               nameEn: 'Slovakia',                     sortOrder: 100 },
  { code: 'SI', name: 'スロベニア',               nameEn: 'Slovenia',                     sortOrder: 100 },
  { code: 'SC', name: 'セーシェル',               nameEn: 'Seychelles',                   sortOrder: 100 },
  { code: 'SN', name: 'セネガル',                 nameEn: 'Senegal',                      sortOrder: 100 },
  { code: 'KN', name: 'セントクリストファー・ネービス', nameEn: 'Saint Kitts and Nevis', sortOrder: 100 },
  { code: 'LC', name: 'セントルシア',             nameEn: 'Saint Lucia',                  sortOrder: 100 },
  { code: 'VC', name: 'セントビンセント・グレナディーン', nameEn: 'Saint Vincent and the Grenadines', sortOrder: 100 },
  { code: 'SO', name: 'ソマリア',                 nameEn: 'Somalia',                      sortOrder: 100 },
  { code: 'SB', name: 'ソロモン諸島',             nameEn: 'Solomon Islands',              sortOrder: 100 },
  { code: 'TD', name: 'チャド',                   nameEn: 'Chad',                         sortOrder: 100 },
  { code: 'CF', name: '中央アフリカ共和国',       nameEn: 'Central African Republic',     sortOrder: 100 },
  { code: 'TN', name: 'チュニジア',               nameEn: 'Tunisia',                      sortOrder: 100 },
  { code: 'CZ', name: 'チェコ',                   nameEn: 'Czech Republic',               sortOrder: 100 },
  { code: 'CL', name: 'チリ',                     nameEn: 'Chile',                        sortOrder: 100 },
  { code: 'TL', name: '東ティモール',             nameEn: 'Timor-Leste',                  sortOrder: 100 },
  { code: 'TG', name: 'トーゴ',                   nameEn: 'Togo',                         sortOrder: 100 },
  { code: 'TO', name: 'トンガ',                   nameEn: 'Tonga',                        sortOrder: 100 },
  { code: 'TT', name: 'トリニダード・トバゴ',     nameEn: 'Trinidad and Tobago',          sortOrder: 100 },
  { code: 'TM', name: 'トルクメニスタン',         nameEn: 'Turkmenistan',                 sortOrder: 100 },
  { code: 'TR', name: 'トルコ',                   nameEn: 'Turkey',                       sortOrder: 100 },
  { code: 'TV', name: 'ツバル',                   nameEn: 'Tuvalu',                       sortOrder: 100 },
  { code: 'DK', name: 'デンマーク',               nameEn: 'Denmark',                      sortOrder: 100 },
  { code: 'DO', name: 'ドミニカ共和国',           nameEn: 'Dominican Republic',           sortOrder: 100 },
  { code: 'DM', name: 'ドミニカ国',               nameEn: 'Dominica',                     sortOrder: 100 },
  { code: 'NI', name: 'ニカラグア',               nameEn: 'Nicaragua',                    sortOrder: 100 },
  { code: 'NE', name: 'ニジェール',               nameEn: 'Niger',                        sortOrder: 100 },
  { code: 'NZ', name: 'ニュージーランド',         nameEn: 'New Zealand',                  sortOrder: 100 },
  { code: 'NR', name: 'ナウル',                   nameEn: 'Nauru',                        sortOrder: 100 },
  { code: 'NA', name: 'ナミビア',                 nameEn: 'Namibia',                      sortOrder: 100 },
  { code: 'NG', name: 'ナイジェリア',             nameEn: 'Nigeria',                      sortOrder: 100 },
  { code: 'NO', name: 'ノルウェー',               nameEn: 'Norway',                       sortOrder: 100 },
  { code: 'HT', name: 'ハイチ',                   nameEn: 'Haiti',                        sortOrder: 100 },
  { code: 'PK', name: 'パキスタン',               nameEn: 'Pakistan',                     sortOrder: 100 },
  { code: 'PW', name: 'パラオ',                   nameEn: 'Palau',                        sortOrder: 100 },
  { code: 'PY', name: 'パラグアイ',               nameEn: 'Paraguay',                     sortOrder: 100 },
  { code: 'PS', name: 'パレスチナ',               nameEn: 'Palestine',                    sortOrder: 100 },
  { code: 'PA', name: 'パナマ',                   nameEn: 'Panama',                       sortOrder: 100 },
  { code: 'PG', name: 'パプアニューギニア',       nameEn: 'Papua New Guinea',             sortOrder: 100 },
  { code: 'VU', name: 'バヌアツ',                 nameEn: 'Vanuatu',                      sortOrder: 100 },
  { code: 'BS', name: 'バハマ',                   nameEn: 'Bahamas',                      sortOrder: 100 },
  { code: 'BH', name: 'バーレーン',               nameEn: 'Bahrain',                      sortOrder: 100 },
  { code: 'BB', name: 'バルバドス',               nameEn: 'Barbados',                     sortOrder: 100 },
  { code: 'VA', name: 'バチカン',                 nameEn: 'Vatican City',                 sortOrder: 100 },
  { code: 'HU', name: 'ハンガリー',               nameEn: 'Hungary',                      sortOrder: 100 },
  { code: 'FJ', name: 'フィジー',                 nameEn: 'Fiji',                         sortOrder: 100 },
  { code: 'FI', name: 'フィンランド',             nameEn: 'Finland',                      sortOrder: 100 },
  { code: 'BT', name: 'ブータン',                 nameEn: 'Bhutan',                       sortOrder: 100 },
  { code: 'BG', name: 'ブルガリア',               nameEn: 'Bulgaria',                     sortOrder: 100 },
  { code: 'BF', name: 'ブルキナファソ',           nameEn: 'Burkina Faso',                 sortOrder: 100 },
  { code: 'BN', name: 'ブルネイ',                 nameEn: 'Brunei',                       sortOrder: 100 },
  { code: 'BI', name: 'ブルンジ',                 nameEn: 'Burundi',                      sortOrder: 100 },
  { code: 'VE', name: 'ベネズエラ',               nameEn: 'Venezuela',                    sortOrder: 100 },
  { code: 'BY', name: 'ベラルーシ',               nameEn: 'Belarus',                      sortOrder: 100 },
  { code: 'BE', name: 'ベルギー',                 nameEn: 'Belgium',                      sortOrder: 100 },
  { code: 'BZ', name: 'ベリーズ',                 nameEn: 'Belize',                       sortOrder: 100 },
  { code: 'PE', name: 'ペルー',                   nameEn: 'Peru',                         sortOrder: 100 },
  { code: 'BJ', name: 'ベナン',                   nameEn: 'Benin',                        sortOrder: 100 },
  { code: 'PL', name: 'ポーランド',               nameEn: 'Poland',                       sortOrder: 100 },
  { code: 'BO', name: 'ボリビア',                 nameEn: 'Bolivia',                      sortOrder: 100 },
  { code: 'PT', name: 'ポルトガル',               nameEn: 'Portugal',                     sortOrder: 100 },
  { code: 'BA', name: 'ボスニア・ヘルツェゴビナ', nameEn: 'Bosnia and Herzegovina',       sortOrder: 100 },
  { code: 'BW', name: 'ボツワナ',                 nameEn: 'Botswana',                     sortOrder: 100 },
  { code: 'HN', name: 'ホンジュラス',             nameEn: 'Honduras',                     sortOrder: 100 },
  { code: 'MG', name: 'マダガスカル',             nameEn: 'Madagascar',                   sortOrder: 100 },
  { code: 'MW', name: 'マラウイ',                 nameEn: 'Malawi',                       sortOrder: 100 },
  { code: 'ML', name: 'マリ',                     nameEn: 'Mali',                         sortOrder: 100 },
  { code: 'MT', name: 'マルタ',                   nameEn: 'Malta',                        sortOrder: 100 },
  { code: 'MY', name: 'マレーシア',               nameEn: 'Malaysia',                     sortOrder: 100 },
  { code: 'MH', name: 'マーシャル諸島',           nameEn: 'Marshall Islands',             sortOrder: 100 },
  { code: 'MV', name: 'モルディブ',               nameEn: 'Maldives',                     sortOrder: 100 },
  { code: 'MD', name: 'モルドバ',                 nameEn: 'Moldova',                      sortOrder: 100 },
  { code: 'MC', name: 'モナコ',                   nameEn: 'Monaco',                       sortOrder: 100 },
  { code: 'MN', name: 'モンゴル',                 nameEn: 'Mongolia',                     sortOrder: 100 },
  { code: 'ME', name: 'モンテネグロ',             nameEn: 'Montenegro',                   sortOrder: 100 },
  { code: 'MR', name: 'モーリタニア',             nameEn: 'Mauritania',                   sortOrder: 100 },
  { code: 'MU', name: 'モーリシャス',             nameEn: 'Mauritius',                    sortOrder: 100 },
  { code: 'MZ', name: 'モザンビーク',             nameEn: 'Mozambique',                   sortOrder: 100 },
  { code: 'MA', name: 'モロッコ',                 nameEn: 'Morocco',                      sortOrder: 100 },
  { code: 'MX', name: 'メキシコ',                 nameEn: 'Mexico',                       sortOrder: 100 },
  { code: 'FM', name: 'ミクロネシア',             nameEn: 'Micronesia',                   sortOrder: 100 },
  { code: 'JO', name: 'ヨルダン',                 nameEn: 'Jordan',                       sortOrder: 100 },
  { code: 'LA', name: 'ラオス',                   nameEn: 'Laos',                         sortOrder: 100 },
  { code: 'LV', name: 'ラトビア',                 nameEn: 'Latvia',                       sortOrder: 100 },
  { code: 'LB', name: 'レバノン',                 nameEn: 'Lebanon',                      sortOrder: 100 },
  { code: 'LS', name: 'レソト',                   nameEn: 'Lesotho',                      sortOrder: 100 },
  { code: 'LY', name: 'リビア',                   nameEn: 'Libya',                        sortOrder: 100 },
  { code: 'LI', name: 'リヒテンシュタイン',       nameEn: 'Liechtenstein',                sortOrder: 100 },
  { code: 'LR', name: 'リベリア',                 nameEn: 'Liberia',                      sortOrder: 100 },
  { code: 'LT', name: 'リトアニア',               nameEn: 'Lithuania',                    sortOrder: 100 },
  { code: 'LU', name: 'ルクセンブルク',           nameEn: 'Luxembourg',                   sortOrder: 100 },
  { code: 'RW', name: 'ルワンダ',                 nameEn: 'Rwanda',                       sortOrder: 100 },
  { code: 'RO', name: 'ルーマニア',               nameEn: 'Romania',                      sortOrder: 100 },
  { code: 'RU', name: 'ロシア',                   nameEn: 'Russia',                       sortOrder: 100 },
  { code: 'MK', name: '北マケドニア',             nameEn: 'North Macedonia',              sortOrder: 100 },
  { code: 'KP', name: '北朝鮮',                   nameEn: 'North Korea',                  sortOrder: 100 },
  { code: 'TJ', name: 'タジキスタン',             nameEn: 'Tajikistan',                   sortOrder: 100 },
  { code: 'TZ', name: 'タンザニア',               nameEn: 'Tanzania',                     sortOrder: 100 },
  { code: 'RS', name: 'セルビア',                 nameEn: 'Serbia',                       sortOrder: 100 },
  { code: 'GQ', name: '赤道ギニア',               nameEn: 'Equatorial Guinea',            sortOrder: 100 },
];

async function main() {
  console.log(`🌍 国マスタ投入開始（${countries.length}件）...`);

  let upserted = 0;
  for (const c of countries) {
    await prisma.country.upsert({
      where: { code: c.code },
      update: {
        name: c.name,
        nameEn: c.nameEn,
        sortOrder: c.sortOrder,
      },
      create: {
        code: c.code,
        name: c.name,
        nameEn: c.nameEn,
        sortOrder: c.sortOrder,
      },
    });
    upserted++;
  }

  console.log(`✅ 完了: ${upserted}件をupsert（既存データは更新、新規は追加）`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
